<div class="image">

  <img style="float: right;" src="https://pku.org.uk/head.png" width="45%" align="right">
      <h4>
          <p style="font-size:25pt">UK19B307 AI Analytics</p>
          <p style="font-size:15pt">Quiz 3</p>
      </h4>
<h5>
    <p> Peking University</p>
    <p> Demonstrable Labs</p>
</h5>
</div>

### Please doule click this block and enter your name / ID:

- Name: Zhang Ziqing
- ID: 1901212856

In [1]:
import numpy as np

<div class="alert alert-warning">
<b>QUESTION 1: </b> 

1, Define a list: `list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

2, Use list comprehension to create a new list which contains elements larger or equal to 3 in `list_1`. Print the new list, the expected output would be: `[3, 4, 5, 6, 7, 8, 9, 10]`
</div>

In [2]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_list = [x for x in list_1 if x>=3]
print(new_list)

[3, 4, 5, 6, 7, 8, 9, 10]


<div class="alert alert-warning">
<b>QUESTION 2: </b> 

1, Define a dictionary with fruit names and prices: `prices = {"banana":0.5, "apple":1, "kiwi":1, "orange":0.8, "pineapple":3.2}`

2, Please calculate the average price of the fruits and print the result. The expected output is `1.3`

In [9]:
prices = {"banana":0.5, "apple":1, "kiwi":1, "orange":0.8, "pineapple":3.2}
price = {y for x,y in prices.items()}
avg= print(sum(price)/len(price))

1.375


<div class="alert alert-warning">
<b>QUESTION 3: </b> 

Using a <b>while</b> loop, calculate the cube sum of the first 10 natural numbers and print the result.

$1^{3}+2^{3}+3^{3}+4^{3}+5^{3}+6^{3}+7^{3}+8^{3}+9^{3}+10^{3}$

<br>
The expected result would be $3025$.
</div>

In [90]:
i = 1
mysum = 0
while i<=10:
    mysum = mysum+i**3
    i=i+1
print(mysum)

3025


<div class="alert alert-warning">

<b>QUESTION 4:</b>

Create a $3$ $x$ $7$ array with integers ranging from 200 to 0 with a step of 10 (in descending order).

Print the array, the expected output is:
    
```
[[200 190 180 170 160 150 140]
 [130 120 110 100  90  80  70]
 [ 60  50  40  30  20  10   0]]```
 
</div>

In [13]:
import numpy as np
print(np.arange(200,-1,-10).reshape(3,7))

[[200 190 180 170 160 150 140]
 [130 120 110 100  90  80  70]
 [ 60  50  40  30  20  10   0]]


<div class="alert alert-warning">
<b>QUESTION 5:</b> 
    
Please print the following string using **ONE LINE** of code:
    
```
Dear Diary,
Today's quiz was "great".
I'm looking forward to the next week's "challenges".
```

</div>

In [91]:
print("""Dear Diary,\nToday\'s quiz was "great".\nI\'m looking forward to the next week\'s "challenges".""")

Dear Diary,
Today's quiz was "great".
I'm looking forward to the next week's "challenges".


<div class="alert alert-warning">
<b>QUESTION 6:</b>

Create a function called `factor_div` wich takes two arguments `x` and `y`. The function returns `x` divided by `y` as an **integer**.

If `y` is not a factor of `x` (`x` can't be divided by `y` without a remainder), the function will raise an `AssertionError` with the message: `Please make sure that the second argument is a factor of the first argument.`
</div>

In [20]:
def factor_div(x,y):
    assert x%y == 0,"Please make sure that the second argument is a factor of the first argument."
    print(int(x/y))

<div class="alert alert-warning">
<b>QUESTION 7:</b>
    
1, Define a list: `list_b = [10, 100, 1000, 10000, 100000, 1000000, 1000000]`

2, Print a slice of `list_b` with the 3 middle elements. The expected output is: 
    
```
[1000, 10000, 100000]```

</div>

In [23]:
list_b = [10, 100, 1000, 10000, 100000, 1000000, 1000000]
print(list_b[2:5])

[1000, 10000, 100000]


<div class="alert alert-warning">
<b>QUESTION 8:</b>
    
1, Define an array: `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3)`

2, Replace the elements in the middle row with 8s. Print the new array, the expected output is:
```
[[0 1 2]
 [8 8 8]
 [6 7 8]]```

</div>

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3)
arr[1,:] = 8
print(arr)

[[0 1 2]
 [8 8 8]
 [6 7 8]]


<div class="alert alert-warning">
<b>QUESTION 9:</b>
    
1, Define two arrays:
    
```python
prices_array = np.array([170.12,  93.29,  55.28, 145.3 , 171.81,  59.5 , 100.5 ]) 
earnings_array = np.array([ 9.2 ,  5.31,  2.41,  5.91, 15.42,  2.51,  6.79])```
    
`prices_array` contains the stock prices for 7 companies and `earnings_array` contains their earnings. 

2, Create a new array called `PE` which contains the PE (price to earnings) ratios for those companies. The PE ratio is calculated by dividing stock price by earnings. Print the new array, the expected output is:
```
[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]```    

</div>

In [35]:
prices_array = np.array([170.12,  93.29,  55.28, 145.3 , 171.81,  59.5 , 100.5 ]) 
earnings_array = np.array([ 9.2 ,  5.31,  2.41,  5.91, 15.42,  2.51,  6.79])
PE = np.array(prices_array / earnings_array)
print(PE)

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


<div class="alert alert-warning">
<b>QUESTION 10:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Select out a subset of all even rows from `arr` and print it. The expected output is:
```
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]```

</div>

In [51]:
arr = np.arange(21).reshape(7,3)
print(arr[[1,3,5],:])

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]


<div class="alert alert-warning">
<b>QUESTION 11:</b>
    
1, Define an array: `data_arr = np.array([[10,2,3],[1,3,3],[2,34,4],[5,4,3]])`

2, For each row in the array, apply the following formula:
    
$x_{1}\times2 + x_{2}\times5 + x_{3}\times3$
    
For instance, if you apply the formula to the first row, you will get 39 ($10\times2 + 2\times5 + 3\times3$).

3, A one-dimensional array will be created after applying the formula to each row. Print the new array, the expected output is:
```
[ 39  26 186  39]```
</div>

In [54]:
data_arr = np.array([[10,2,3],[1,3,3],[2,34,4],[5,4,3]])

for x1,x2,x3 in data_arr[1]:
    print(x1*2+x2*5+x3*3)

TypeError: cannot unpack non-iterable numpy.int64 object

<div class="alert alert-warning">
<b>QUESTION 12:</b>
    
1, Define an array: 
    
```python
arr2d = np.array([[ 2, 10,  8,  7],
                  [20, 13,  5,  2],
                  [17, 14,  1,  3],
                  [ 9, 11, 17, 10],
                  [ 5,  8,  2, 14]])```

2, Sort the values in each column of `arr2d` in ascending order. Print the new array, the expected output is:
```
[[ 2  8  1  2]
 [ 5 10  2  3]
 [ 9 11  5  7]
 [17 13  8 10]
 [20 14 17 14]]```

</div>

In [57]:
arr2d = np.array([[ 2, 10,  8,  7],
                  [20, 13,  5,  2],
                  [17, 14,  1,  3],
                  [ 9, 11, 17, 10],
                  [ 5,  8,  2, 14]])
arr2d.sort()
print(arr2d)

[[ 2  7  8 10]
 [ 2  5 13 20]
 [ 1  3 14 17]
 [ 9 10 11 17]
 [ 2  5  8 14]]


<div class="alert alert-warning">
<b>QUESTION 13:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Print the array below by indexing `arr`.

```    
[[ 7  8]
 [10 11]
 [13 14]]```

</div>

In [59]:
arr = np.arange(21).reshape(7,3)
print(arr[2:5,1:])

[[ 7  8]
 [10 11]
 [13 14]]


<div class="alert alert-warning">
<b>QUESTION 14:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Replace the odd numbers in `arr` with 1s. Print the new array, the expected output is:
```
[[ 0  1  2]
 [ 1  4  1]
 [ 6  1  8]
 [ 1 10  1]
 [12  1 14]
 [ 1 16  1]
 [18  1 20]]```
</div>

In [92]:
arr = np.arange(21).reshape(7,3)
arr[arr%2!=0]=1
print(arr)

[[ 0  1  2]
 [ 1  4  1]
 [ 6  1  8]
 [ 1 10  1]
 [12  1 14]
 [ 1 16  1]
 [18  1 20]]


<div class="alert alert-warning">
<b>QUESTION 15:</b>
    
1, Define a string: `string_NY = 'You know New York, you need New York, you know you need unique New York.'`

2, Write code to count the number of times `New York` occurs in the string `string_NY`. Print the result, the correct output is `3`.
</div>

In [65]:
string_NY = 'You know New York, you need New York, you know you need unique New York.'
print(string_NY.count('New York'))

3


<div class="alert alert-warning">
<b>QUESTION 16: </b> 

Create a $5\times5$ array with 0's on the border and 1's inside (as shown below). Print the array.
```
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]   
```
</div>

In [67]:
arr = np.zeros((5,5))
arr[1:4,1:4] = 1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


<div class="alert alert-warning">
<b>QUESTION 17: </b> 

1, Create a function called `divisible_by_9` using `lambda` statement which returns the argument divided by `9` if the number can be divided by `9` without a remainder. If the argument can't be divided by 9 without a remainder the function should return `0.0` (float number).
    
2, Define a list: `numbers = [9, 15, 18, 22, 27, 42]`

3, Apply the function `divisible_by_9` to all the elements in list `numbers` using `map` function.

4, Print the new list, the expected output is: `[1.0, 0.0, 2.0, 0.0, 3.0, 0.0]`
</div>

In [72]:
def divisible_by_9(list_1):
    list = (lambda x :x%9 == 0,list_1)
numbers = [9, 15, 18, 22, 27, 42]
list(map(lambda x: x %9, list_1))


[1, 2, 3, 4, 5, 6, 7, 8, 0, 1]

<div class="alert alert-warning">
<b>QUESTION 18:</b>

Define a function named `sum_arr` which takes an array with numbers as the argument. The funtion would calculate the sum of the elements in the array and print `The sum of the elements in the array is: ` followed by the result.
 
If we call the function with array `np.array([[1,2,3],[4,5,6],[7,8,9]])`, it would print:

`The sum of the elements in the array is: 45`

In [96]:
def sum_arr(arr):
    sumcol = arr.sum(axis=0)
    res = sumcol.sum(axis=0)
    print("The sum of the elements in the array is:"+str(res))
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum_arr(arr)

The sum of the elements in the array is:45


<div class="alert alert-warning">
<b>QUESTION 19: </b> 
    
Define a list: `list_num = [1, 3, 5, 6, 8]`

Sort the list by the ascending order of the absolute difference between the element and the number `5`. Print the new list, the expected output is:

`[5, 6, 3, 8, 1]`
</div>

In [81]:
list_num = [1, 3, 5, 6, 8]
print(list_num.sort())

None


<div class="alert alert-warning">
<b>QUESTION 20: </b> 

Define a dictionary: 
    
`Shares = {'James':2359, 'Robert':4032, 'Nicolas':1020, 'Louis':2500, 'Bernard': 5538, 'Logan':1330}`

For the dictionary keys end with letter `s`, update the corresponding dictionary values to `2020`. Print the updated dictionary, the expected output would be:

`{'James': 2020, 'Robert': 4032, 'Nicolas': 2020, 'Louis': 2020, 'Bernard': 5538, 'Logan': 1330}`
</div>

In [89]:
Shares = {'James':2359, 'Robert':4032, 'Nicolas':1020, 'Louis':2500, 'Bernard': 5538, 'Logan':1330}
name = {x for x,y in Shares.items()}
print(name.endswith('s'))

AttributeError: 'set' object has no attribute 'endswith'